# Generated by Django 3.2.11 on 2022-02-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
