# Generated by Django 3.2.11 on 2022-02-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre')),
                ('link', models.URLField()),
                ('lugar', models.IntegerField()),
                ('coordenadas', models.CharField(blank=True, max_length=500, verbose_name='coordenadas')),
                ('imagen', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
    ]
