# Generated by Django 3.2.11 on 2022-02-23 09:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_rename_viajesindexpage_viajespage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajespage',
            old_name='introduccionViajes',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='viajespage',
            name='coordenadas',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=50),
        ),
    ]
