# Generated by Django 3.2.11 on 2022-02-28 08:09

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_auto_20220223_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='lugar',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=100, verbose_name='coordenadas'),
        ),
        migrations.AlterField(
            model_name='viajespage',
            name='coordenadas',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=100),
        ),
    ]
